#ifndef SHARED_BUFFER_PROTOCOL_H
#define SHARED_BUFFER_PROTOCOL_H

#define SHARED_BUFFER_PORT 0x0510u
#define SHARED_BUFFER_STATUS_PORT 0x0520u
#define BUFFER_SIZE 256u

#define VM_MODE_READER 0u
#define VM_MODE_WRITER 1u

#endif /* SHARED_BUFFER_PROTOCOL_H */
